[build]
  command = """
  mkdir -p bin
  curl -sL https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz | tar -xJf - --strip-components=1 -C bin --wildcards '*/ffmpeg'
  chmod +x bin/ffmpeg
  """

[build.environment]
  FFMPEG_PATH = "/var/task/bin/ffmpeg"

[functions]
  directory = "/functions"
  included_files = [ "bin/ffmpeg", "README.md" ]

[[redirects]]
  from = "/"
  to = "/.netlify/functions/netlify"
  status = 200
  force = true
